; tabs
[TAB_ORDER]
TAB_1=App
TAB_2=MFD
TAB_3=CSP Data Logger

[ACUIR_TOGGLE_APP]
TAB=App
NAME=Toggle ACUIR On/Off
ORDER=1
ACTIVATION=1
HELP=

[ACUIR_COCKPIT_X]
TAB=MFD
NAME=Nav (Left/Right)
ORDER=1
DN=_R
UP=_L
DN_LABEL=Right
UP_LABEL=Left
HELP=

[ACUIR_COCKPIT_Y]
TAB=MFD
NAME=Nav (Up/Down)
ORDER=2
DN=_DN
UP=_UP
DN_LABEL=Down
UP_LABEL=Up
HELP=

[__APP_CSP_DATA_LOGGER_TOGGLE]
TAB=CSP Data Logger
NAME=Toggle Logging
ORDER=1
ACTIVATION=1
HELP=