; tabs
[TAB_ORDER]
TAB_1=MFD Controls

[ACUIR_COCKPIT_X]
TAB=MFD Controls
NAME=MFD (Left/Right)
ORDER=1
DN=_R
UP=_L
DN_LABEL=Right
UP_LABEL=Left
HELP=

[ACUIR_COCKPIT_Y]
TAB=MFD Controls
NAME=MFD (Up/Down)
ORDER=2
DN=_DN
UP=_UP
DN_LABEL=Down
UP_LABEL=Up
HELP=