local configs = require("configs")
local controls = require("controls")

local gamepadAxisList = {
        [0] = "L2",
        [1] = "R2",
        [2] = "Left stick (Y+)",
        [3] = "Left stick (Y−)",
        [4] = "Right stick (Y+)",
        [5] = "Right stick (Y−)",
        [6] = "Left stick (X+)",
        [7] = "Left stick (X−)",
        [8] = "Right stick (X+)",
        [9] = "Right stick (X−)",
}

local yesNoList = {
        [0] = "No",
        [1] = "Yes",
}

local function newSetting(setting)
        return {
                cfg = setting.cfg or configs.CONTROLS,
                section = setting.section,
                id = setting.id,
                label = setting.label,
                min = setting.min or 0,
                max = setting.max or 1,
                step = setting.step or 0.01,
                shiftStep = setting.shiftStep or 0.05,
                multiplier = setting.multiplier or 100,
                offset = setting.offset or 0,
                format = setting.format or "%.0f %s",
                unit = setting.unit or "%",
                help = setting.help or "",
                graph = setting.graph or false,
                items = setting.items or nil,
        }
end

local controlTweaks = {
        KEYBOARD = {
                {
                        label = "KEYBOARD TWEAKS",
                        content = {
                                {
                                        group = "Keyboard Steering",
                                        tweaks = {
                                                newSetting({
                                                        section = "KEYBOARD",
                                                        id = "STEERING_SPEED",
                                                        label = "Speed",
                                                        min = 0,
                                                        max = 4,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "KEYBOARD",
                                                        id = "STEERING_OPPOSITE_DIRECTION_SPEED",
                                                        label = "Opp. Direction Speed",
                                                        min = 0,
                                                        max = 4,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "KEYBOARD",
                                                        id = "STEER_RESET_SPEED",
                                                        label = "Reset Speed",
                                                        min = 0,
                                                        max = 4,
                                                        multiplier = 100,
                                                }),
                                        },
                                },
                                {
                                        group = "Mouse Steering",
                                        tweaks = {
                                                newSetting({
                                                        section = "KEYBOARD",
                                                        id = "MOUSE_STEER",
                                                        label = "Mouse Steering",
                                                        min = 0,
                                                        max = 1,
                                                        step = 1,
                                                        multiplier = 1,
                                                        items = yesNoList,
                                                }),
                                                newSetting({
                                                        section = "KEYBOARD",
                                                        id = "MOUSE_ACCELERATOR_BRAKE",
                                                        label = "Mouse Accel. and Brake",
                                                        min = 0,
                                                        max = 1,
                                                        step = 1,
                                                        multiplier = 1,
                                                        items = yesNoList,
                                                }),
                                                newSetting({
                                                        cfg = configs.CSPGENERAL,
                                                        section = "CONTROL",
                                                        id = "NO_MOUSE_STEERING_FOR_INACTIVE",
                                                        label = "No mouse steer in background",
                                                        min = 0,
                                                        max = 1,
                                                        step = 1,
                                                        multiplier = 1,
                                                        items = yesNoList,
                                                }),
                                                newSetting({
                                                        section = "KEYBOARD",
                                                        id = "MOUSE_SPEED",
                                                        label = "Speed",
                                                        min = 0,
                                                        max = 3,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "__EXT_KEYBOARD",
                                                        id = "SHIFT_WITH_WHEEL",
                                                        label = "Shift gears with mouse wheel",
                                                        min = 0,
                                                        max = 1,
                                                        step = 1,
                                                        multiplier = 1,
                                                        items = yesNoList,
                                                }),
                                                newSetting({
                                                        section = "__EXT_KEYBOARD",
                                                        id = "SHIFT_WITH_XBUTTONS",
                                                        label = "Shift with 4th and 5th buttons",
                                                        min = 0,
                                                        max = 1,
                                                        step = 1,
                                                        multiplier = 1,
                                                        items = yesNoList,
                                                }),
                                        },
                                },
                                {
                                        group = "Forced Throttle",
                                        tweaks = {
                                                newSetting({
                                                        section = "__EXT_KEYBOARD_GAS_RAW",
                                                        id = "OVERRIDE",
                                                        label = "Enable Forced Throttle",
                                                        min = 0,
                                                        max = 1,
                                                        step = 1,
                                                        multiplier = 1,
                                                        items = yesNoList,
                                                }),
                                                newSetting({
                                                        section = "__EXT_KEYBOARD_GAS_RAW",
                                                        id = "LAG_UP",
                                                        label = "Filter (up)",
                                                        min = 0,
                                                        max = 0.99,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "__EXT_KEYBOARD_GAS_RAW",
                                                        id = "LAG_DOWN",
                                                        label = "Filter (down)",
                                                        min = 0,
                                                        max = 0.99,
                                                        multiplier = 100,
                                                }),
                                        },
                                },
                        },
                },
        },
        X360 = {
                {
                        label = "GAMEPAD TWEAKS",
                        content = {
                                {
                                        group = "Steering",
                                        tweaks = {
                                                newSetting({
                                                        section = "X360",
                                                        id = "STEER_SPEED",
                                                        label = "Speed",
                                                        min = 0,
                                                        max = 2,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "X360",
                                                        id = "STEER_GAMMA",
                                                        label = "Gamma",
                                                        min = 1,
                                                        max = 5,
                                                        multiplier = 100,
                                                        graph = true,
                                                }),
                                                newSetting({
                                                        section = "X360",
                                                        id = "STEER_FILTER",
                                                        label = "Filter",
                                                        min = 0,
                                                        max = 1,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "X360",
                                                        id = "SPEED_SENSITIVITY",
                                                        label = "Speed Sensitivity",
                                                        min = 0,
                                                        max = 1,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "X360",
                                                        id = "STEER_DEADZONE",
                                                        label = "Deadzone",
                                                        min = 0,
                                                        max = 1,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "X360",
                                                        id = "RUMBLE_INTENSITY",
                                                        label = "Rumble Intensity",
                                                        min = 0,
                                                        max = 1,
                                                        multiplier = 100,
                                                }),
                                        },
                                },
                                {
                                        group = "Tweaks",
                                        tweaks = {
                                                newSetting({
                                                        section = "X360",
                                                        id = "AXIS_REMAP_THROTTLE",
                                                        label = "Remap Throttle",
                                                        min = 0,
                                                        step = 1,
                                                        max = #gamepadAxisList - 1,
                                                        multiplier = 1,
                                                        items = gamepadAxisList,
                                                }),
                                                newSetting({
                                                        section = "X360",
                                                        id = "AXIS_REMAP_BRAKES",
                                                        label = "Remap Brakes",
                                                        min = 0,
                                                        step = 1,
                                                        max = #gamepadAxisList - 1,
                                                        multiplier = 1,
                                                        items = gamepadAxisList,
                                                }),
                                        },
                                },
                        },
                },
        },
        WHEEL = {

                {
                        label = "AXIS",
                        content = {
                                {
                                        group = "Steering",
                                        tweaks = {
                                                newSetting({
                                                        section = "STEER",
                                                        id = "SPEED_SENSITIVITY",
                                                        label = "Steer Sensitivity",
                                                }),
                                                newSetting({
                                                        section = "STEER",
                                                        id = "STEER_GAMMA",
                                                        label = "Steer Gamma",
                                                        min = 0.2,
                                                        max = 4,
                                                        multiplier = 100,
                                                        graph = true,
                                                }),
                                        },
                                },
                                {
                                        group = "Others",
                                        tweaks = {

                                                newSetting({
                                                        section = "THROTTLE",
                                                        id = "GAMMA",
                                                        label = "Throttle Gamma",
                                                        min = 0.01,
                                                        max = 5,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                        graph = true,
                                                }),
                                                newSetting({
                                                        section = "BRAKES",
                                                        id = "GAMMA",
                                                        label = "Brake Gamma",
                                                        min = 0.01,
                                                        max = 5,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                        graph = true,
                                                }),
                                                newSetting({
                                                        section = "CLUTCH",
                                                        id = "GAMMA",
                                                        label = "Clutch Gamma",
                                                        min = 0.01,
                                                        max = 5,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                        graph = true,
                                                }),
                                                newSetting({
                                                        section = "HANDBRAKE",
                                                        id = "GAMMA",
                                                        label = "Handbrake Gamma",
                                                        min = 0.01,
                                                        max = 5,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                        graph = true,
                                                }),

                                                newSetting({
                                                        section = "STEER",
                                                        id = "DEBOUNCING_MS",
                                                        label = "Debounce",
                                                        min = 0,
                                                        max = 200,
                                                        step = 1,
                                                        multiplier = 1,
                                                        unit = "ms",
                                                }),
                                        },
                                },
                        },
                },
                {
                        label = "FFB",
                        content = {
                                {
                                        group = "FFB",
                                        tweaks = {
                                                newSetting({
                                                        section = "STEER",
                                                        id = "FF_GAIN",
                                                        label = "Gain",
                                                        min = 0,
                                                        max = 2,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                }),
                                                newSetting({ section = "STEER", id = "FILTER_FF", label = "Filter" }),
                                                newSetting({
                                                        section = "FF_SKIP_STEPS",
                                                        id = "VALUE",
                                                        label = "Skip Steps",
                                                        min = 0,
                                                        max = 10,
                                                        step = 1,
                                                        multiplier = 1,
                                                        unit = "steps",
                                                }),
                                        },
                                },
                                {
                                        group = "FFB Tweaks",
                                        tweaks = {
                                                newSetting({
                                                        section = "FF_TWEAKS",
                                                        id = "MIN_FF",
                                                        label = "Minimum Force",
                                                        min = 0,
                                                        max = 1,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "FF_TWEAKS",
                                                        id = "CENTER_BOOST_GAIN",
                                                        label = "Center Boost Gain",
                                                        min = 0,
                                                        max = 10,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "FF_TWEAKS",
                                                        id = "CENTER_BOOST_RANGE",
                                                        label = "Center Boost Range",
                                                        min = 0,
                                                        max = 1,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                }),
                                        },
                                },

                                {
                                        group = "FFB Enhancements",
                                        tweaks = {
                                                newSetting({
                                                        section = "FF_ENHANCEMENT",
                                                        id = "CURBS",
                                                        label = "Curbs",
                                                        min = 0,
                                                        max = 2,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "FF_ENHANCEMENT",
                                                        id = "ROAD",
                                                        label = "Road",
                                                        min = 0,
                                                        max = 2,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "FF_ENHANCEMENT",
                                                        id = "SLIPS",
                                                        label = "Slips",
                                                        min = 0,
                                                        max = 2,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                }),
                                                newSetting({
                                                        section = "FF_ENHANCEMENT",
                                                        id = "ABS",
                                                        label = "ABS",
                                                        min = 0,
                                                        max = 2,
                                                        step = 0.01,
                                                        multiplier = 100,
                                                }),
                                                -- newSetting({
                                                --         section = "FF_ENHANCEMENT_2",
                                                --         id = "UNDERSTEER",
                                                --         label = "Understeer",
                                                --         min = 0,
                                                --         max = 2,
                                                --         step = 0.01,
                                                --         multiplier = 100,
                                                -- }),
                                        },
                                },
                                -- {
                                --         group = "Low Speed FFB Reduction",
                                --         tweaks = {
                                --                 newSetting({
                                --                         cfg = controls.cfg.system,
                                --                         section = "LOW_SPEED_FF",
                                --                         id = "SPEED_KMH",
                                --                         label = "Speed Threshold",
                                --                         min = 0,
                                --                         max = 30,
                                --                         step = 1,
                                --                         multiplier = 1,
                                --                         unit = "km/h",
                                --                 }),
                                --                 newSetting({
                                --                         cfg = controls.cfg.system,
                                --                         section = "LOW_SPEED_FF",
                                --                         id = "MIN_VALUE",
                                --                         label = "Min. Level",
                                --                         min = 0,
                                --                         max = 2,
                                --                         step = 0.01,
                                --                         multiplier = 100,
                                --                 }),
                                --         },
                                -- },

                                -- {
                                --         group = "FFB Damper",
                                --         tweaks = {
                                --                 newSetting({
                                --                         cfg = controls.cfg.system,
                                --                         section = "FF_EXPERIMENTAL",
                                --                         id = "DAMPER_GAIN",
                                --                         label = "Gain",
                                --                         min = 0,
                                --                         max = 2,
                                --                         step = 0.01,
                                --                         multiplier = 100,
                                --                 }),
                                --                 newSetting({
                                --                         cfg = controls.cfg.system,
                                --                         section = "FF_EXPERIMENTAL",
                                --                         id = "DAMPER_MIN_LEVEL",
                                --                         label = "Min. Level",
                                --                         min = 0,
                                --                         max = 2,
                                --                         step = 0.01,
                                --                         multiplier = 100,
                                --                 }),
                                --         },
                                -- },
                        },
                },
        },
}

return controlTweaks
