local keys = {
        keyList = {
                [ac.KeyIndex.Cancel] = { string = "Cancel", hex = "0x03" },
                [ac.KeyIndex.MiddleButton] = { string = "MiddleButton", hex = "0x04" },
                [ac.KeyIndex.XButton1] = { string = "XButton1", hex = "0x05" },
                [ac.KeyIndex.XButton2] = { string = "XButton2", hex = "0x06" },
                [ac.KeyIndex.Back] = { string = "Back", hex = "0x08" },
                [ac.KeyIndex.Tab] = { string = "Tab", hex = "0x09" },
                [ac.KeyIndex.Clear] = { string = "Clear", hex = "0x0C" },
                [ac.KeyIndex.Return] = { string = "Return", hex = "0x0D" },
                [ac.KeyIndex.Shift] = { string = "Shift", hex = "0x10" },
                [ac.KeyIndex.Control] = { string = "Ctrl", hex = "0x11" },
                [ac.KeyIndex.Menu] = { string = "Alt", hex = "0x12" },
                [ac.KeyIndex.Pause] = { string = "Pause", hex = "0x13" },
                [ac.KeyIndex.Capital] = { string = "Capital", hex = "0x14" },
                [ac.KeyIndex.Kana] = { string = "Kana", hex = "0x15" },
                [ac.KeyIndex.Junja] = { string = "Junja", hex = "0x17" },
                [ac.KeyIndex.Final] = { string = "Final", hex = "0x18" },
                [ac.KeyIndex.Hanja] = { string = "Hanja", hex = "0x19" },
                [ac.KeyIndex.Escape] = { string = "Escape", hex = "0x1B" },
                [ac.KeyIndex.Convert] = { string = "Convert", hex = "0x1C" },
                [ac.KeyIndex.NonConvert] = { string = "NonConvert", hex = "0x1D" },
                [ac.KeyIndex.Accept] = { string = "Accept", hex = "0x1E" },
                [ac.KeyIndex.ModeChange] = { string = "ModeChange", hex = "0x1F" },
                [ac.KeyIndex.Space] = { string = "Space", hex = "0x20" },
                [ac.KeyIndex.PageUp] = { string = "PageUp", hex = "0x21" },
                [ac.KeyIndex.PageDown] = { string = "PageDown", hex = "0x22" },
                [ac.KeyIndex.End] = { string = "End", hex = "0x23" },
                [ac.KeyIndex.Home] = { string = "Home", hex = "0x24" },
                [ac.KeyIndex.Left] = { string = "Left", hex = "0x25" },
                [ac.KeyIndex.Up] = { string = "Up", hex = "0x26" },
                [ac.KeyIndex.Right] = { string = "Right", hex = "0x27" },
                [ac.KeyIndex.Down] = { string = "Down", hex = "0x28" },
                [ac.KeyIndex.Select] = { string = "Select", hex = "0x29" },
                [ac.KeyIndex.Print] = { string = "Print", hex = "0x2A" },
                [ac.KeyIndex.Execute] = { string = "Execute", hex = "0x2B" },
                [ac.KeyIndex.Snapshot] = { string = "Snapshot", hex = "0x2C" },
                [ac.KeyIndex.Insert] = { string = "Insert", hex = "0x2D" },
                [ac.KeyIndex.Delete] = { string = "Delete", hex = "0x2E" },
                [ac.KeyIndex.Help] = { string = "Help", hex = "0x2F" },
                [ac.KeyIndex.D0] = { string = "0", hex = "0x30" },
                [ac.KeyIndex.D1] = { string = "1", hex = "0x31" },
                [ac.KeyIndex.D2] = { string = "2", hex = "0x32" },
                [ac.KeyIndex.D3] = { string = "3", hex = "0x33" },
                [ac.KeyIndex.D4] = { string = "4", hex = "0x34" },
                [ac.KeyIndex.D5] = { string = "5", hex = "0x35" },
                [ac.KeyIndex.D6] = { string = "6", hex = "0x36" },
                [ac.KeyIndex.D7] = { string = "7", hex = "0x37" },
                [ac.KeyIndex.D8] = { string = "8", hex = "0x38" },
                [ac.KeyIndex.D9] = { string = "9", hex = "0x39" },
                [ac.KeyIndex.A] = { string = "A", hex = "0x41" },
                [ac.KeyIndex.B] = { string = "B", hex = "0x42" },
                [ac.KeyIndex.C] = { string = "C", hex = "0x43" },
                [ac.KeyIndex.D] = { string = "D", hex = "0x44" },
                [ac.KeyIndex.E] = { string = "E", hex = "0x45" },
                [ac.KeyIndex.F] = { string = "F", hex = "0x46" },
                [ac.KeyIndex.G] = { string = "G", hex = "0x47" },
                [ac.KeyIndex.H] = { string = "H", hex = "0x48" },
                [ac.KeyIndex.I] = { string = "I", hex = "0x49" },
                [ac.KeyIndex.J] = { string = "J", hex = "0x4A" },
                [ac.KeyIndex.K] = { string = "K", hex = "0x4B" },
                [ac.KeyIndex.L] = { string = "L", hex = "0x4C" },
                [ac.KeyIndex.M] = { string = "M", hex = "0x4D" },
                [ac.KeyIndex.N] = { string = "N", hex = "0x4E" },
                [ac.KeyIndex.O] = { string = "O", hex = "0x4F" },
                [ac.KeyIndex.P] = { string = "P", hex = "0x50" },
                [ac.KeyIndex.Q] = { string = "Q", hex = "0x51" },
                [ac.KeyIndex.R] = { string = "R", hex = "0x52" },
                [ac.KeyIndex.S] = { string = "S", hex = "0x53" },
                [ac.KeyIndex.T] = { string = "T", hex = "0x54" },
                [ac.KeyIndex.U] = { string = "U", hex = "0x55" },
                [ac.KeyIndex.V] = { string = "V", hex = "0x56" },
                [ac.KeyIndex.W] = { string = "W", hex = "0x57" },
                [ac.KeyIndex.X] = { string = "X", hex = "0x58" },
                [ac.KeyIndex.Y] = { string = "Y", hex = "0x59" },
                [ac.KeyIndex.Z] = { string = "Z", hex = "0x5A" },
                [ac.KeyIndex.LeftWin] = { string = "LeftWin", hex = "0x5B" },
                [ac.KeyIndex.RightWin] = { string = "RightWin", hex = "0x5C" },
                [ac.KeyIndex.Apps] = { string = "Apps", hex = "0x5D" },
                [ac.KeyIndex.Sleep] = { string = "Sleep", hex = "0x5F" },
                [ac.KeyIndex.NumPad0] = { string = "NumPad0", hex = "0x60" },
                [ac.KeyIndex.NumPad1] = { string = "NumPad1", hex = "0x61" },
                [ac.KeyIndex.NumPad2] = { string = "NumPad2", hex = "0x62" },
                [ac.KeyIndex.NumPad3] = { string = "NumPad3", hex = "0x63" },
                [ac.KeyIndex.NumPad4] = { string = "NumPad4", hex = "0x64" },
                [ac.KeyIndex.NumPad5] = { string = "NumPad5", hex = "0x65" },
                [ac.KeyIndex.NumPad6] = { string = "NumPad6", hex = "0x66" },
                [ac.KeyIndex.NumPad7] = { string = "NumPad7", hex = "0x67" },
                [ac.KeyIndex.NumPad8] = { string = "NumPad8", hex = "0x68" },
                [ac.KeyIndex.NumPad9] = { string = "NumPad9", hex = "0x69" },
                [ac.KeyIndex.Multiply] = { string = "Multiply", hex = "0x6A" },
                [ac.KeyIndex.Add] = { string = "Add", hex = "0x6B" },
                [ac.KeyIndex.Separator] = { string = "Separator", hex = "0x6C" },
                [ac.KeyIndex.Subtract] = { string = "Subtract", hex = "0x6D" },
                [ac.KeyIndex.Decimal] = { string = "Decimal", hex = "0x6E" },
                [ac.KeyIndex.Divide] = { string = "Divide", hex = "0x6F" },
                [ac.KeyIndex.F1] = { string = "F1", hex = "0x70" },
                [ac.KeyIndex.F2] = { string = "F2", hex = "0x71" },
                [ac.KeyIndex.F3] = { string = "F3", hex = "0x72" },
                [ac.KeyIndex.F4] = { string = "F4", hex = "0x73" },
                [ac.KeyIndex.F5] = { string = "F5", hex = "0x74" },
                [ac.KeyIndex.F6] = { string = "F6", hex = "0x75" },
                [ac.KeyIndex.F7] = { string = "F7", hex = "0x76" },
                [ac.KeyIndex.F8] = { string = "F8", hex = "0x77" },
                [ac.KeyIndex.F9] = { string = "F9", hex = "0x78" },
                [ac.KeyIndex.F10] = { string = "F10", hex = "0x79" },
                [ac.KeyIndex.F11] = { string = "F11", hex = "0x7A" },
                [ac.KeyIndex.F12] = { string = "F12", hex = "0x7B" },
                [ac.KeyIndex.F13] = { string = "F13", hex = "0x7C" },
                [ac.KeyIndex.F14] = { string = "F14", hex = "0x7D" },
                [ac.KeyIndex.F15] = { string = "F15", hex = "0x7E" },
                [ac.KeyIndex.F16] = { string = "F16", hex = "0x7F" },
                [ac.KeyIndex.F17] = { string = "F17", hex = "0x80" },
                [ac.KeyIndex.F18] = { string = "F18", hex = "0x81" },
                [ac.KeyIndex.F19] = { string = "F19", hex = "0x82" },
                [ac.KeyIndex.F20] = { string = "F20", hex = "0x83" },
                [ac.KeyIndex.F21] = { string = "F21", hex = "0x84" },
                [ac.KeyIndex.F22] = { string = "F22", hex = "0x85" },
                [ac.KeyIndex.F23] = { string = "F23", hex = "0x86" },
                [ac.KeyIndex.F24] = { string = "F24", hex = "0x87" },
                [ac.KeyIndex.NumLock] = { string = "NumLock", hex = "0x90" },
                [ac.KeyIndex.Scroll] = { string = "Scroll", hex = "0x91" },
                [ac.KeyIndex.Oem1] = { string = ";", hex = "0xBA" },
                [ac.KeyIndex.OemPlus] = { string = "+", hex = "0xBB" },
                [ac.KeyIndex.OemComma] = { string = ",", hex = "0xBC" },
                [ac.KeyIndex.OemMinus] = { string = "-", hex = "0xBD" },
                [ac.KeyIndex.OemPeriod] = { string = ".", hex = "0xBE" },
                [ac.KeyIndex.Oem2] = { string = "/", hex = "0xBF" },
                [ac.KeyIndex.Oem3] = { string = "`", hex = "0xC0" },
                [ac.KeyIndex.SquareOpenBracket] = { string = "[", hex = "0xDB" },
                [ac.KeyIndex.SquareCloseBracket] = { string = "]", hex = "0xDD" },
        },
        indexStringList = {},
        indexHexList = {},
        hexIndexList = {},
        hexStringList = {},
}

function keys:indexToString(keyIndex)
        local string = keys.indexStringList[tonumber(keyIndex)]

        return string or "Unknown"
end

for k, v in pairs(keys.keyList) do
        keys.indexStringList[k] = v.string
        keys.indexHexList[k] = v.hex
        keys.hexIndexList[v.hex] = k
        keys.hexStringList[v.hex] = v.string
end

return keys
