local weather = {
        typeString = {
                [0] = "Light Thunderstorm",
                "Thunderstorm",
                "Heavy Thunderstorm",
                "Light Drizzle",
                "Drizzle",
                "Heavy Drizzle",
                "LightRain",
                "Rain",
                "Heavy Rain",
                "LightSnow",
                "Snow",
                "Heavy Snow",
                "Light Sleet",
                "Sleet",
                "Heavy Sleet",
                "Clear",
                "Few Clouds",
                "Scattered Clouds",
                "Broken Clouds",
                "Overcast Clouds",
                "Fog",
                "Mist",
                "Smoke",
                "Haze",
                "Sand",
                "Dust",
                "Squalls",
                "Tornado",
                "Hurricane",
                "Cold",
                "Hot",
                "Windy",
                "Hail",
        },
        typeIcon = {
                [0] = ui.Icons.WeatherStormLight,
                ui.Icons.WeatherStorm,
                ui.Icons.WeatherStorm,
                ui.Icons.WeatherDrizzle,
                ui.Icons.WeatherDrizzle,
                ui.Icons.WeatherDrizzle,
                ui.Icons.WeatherRainLight,
                ui.Icons.WeatherRain,
                ui.Icons.WeatherRain,
                ui.Icons.WeatherSnowLight,
                ui.Icons.WeatherSnow,
                ui.Icons.WeatherSnow,
                ui.Icons.WeatherHail,
                ui.Icons.WeatherHail,
                ui.Icons.WeatherHail,
                ui.Icons.WeatherClear,
                ui.Icons.WeatherFewClouds,
                ui.Icons.WeatherFewClouds,
                ui.Icons.WeatherOvercast,
                ui.Icons.WeatherOvercast,
                ui.Icons.WeatherFog,
                ui.Icons.WeatherFog,
                ui.Icons.WeatherFog,
                ui.Icons.WeatherFog,
                ui.Icons.WeatherFog,
                ui.Icons.WeatherFog,
                ui.Icons.WeatherWindy,
                ui.Icons.WeatherTornado,
                ui.Icons.WeatherTornado,
                ui.Icons.WeatherCold,
                ui.Icons.WeatherHot,
                ui.Icons.WeatherWindy,
                ui.Icons.WeatherHail,
        },
}

return weather
